spring:
  datasource:
    url: ${DB_URL}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

server:
  port: 8080

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MariaDBDialect
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
